[tox]
envlist =
    py{310,311,312,313}-django52
    py{312,313}-django60

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313

[testenv]
commands =
    coverage run --branch --source=notifications_sites manage.py test
deps =
    coverage
    django-notifications-community>=1.12
    django52: Django>=5.2,<5.3
    django60: Django>=6.0,<6.1
